export const USER_MESSAGE_REQUEST = "USER_MESSAGE_REQUEST"
export const USER_MESSAGE_SUCCESS = "USER_MESSAGE_SUCCESS"
export const USER_MESSAGE_FAIL = "USER_MESSAGE_FAIL"

export const MESSAGE_SENT_REQUEST = "MESSAGE_SENT_REQUEST"
export const MESSAGE_SENT_SUCCESS = "MESSAGE_SENT_SUCCESS"
export const MESSAGE_SENT_FAIL = "MESSAGE_SENT_FAIL"