export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST"
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS"
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL"

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST"
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS"
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL"

export const LOGOUT_USER_REQUEST = "LOGOUT_USER_REQUEST"
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS"
export const LOGOUT_USER_FAIL = "LOGOUT_USER_FAIL"

export const OTHER_USER_REQUEST = "OTHER_USER_REQUEST"
export const OTHER_USER_SUCCESS = "OTHER_USER_SUCCESS"
export const OTHER_USER_FAIL = "OTHER_USER_FAIL"

export const OTHER_USER_DETAIL_REQUEST = "OTHER_USER_DETAIL_REQUEST"
export const OTHER_USER_DETAIL_SUCCESS = "OTHER_USER_DETAIL_SUCCESS"
export const OTHER_USER_DETAIL_FAIL = "OTHER_USER_DETAIL_FAIL"

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST"
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS"
export const LOAD_USER_FAIL = "LOAD_USER_FAIL"